# Generated by Django 5.0.1 on 2024-10-18 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('operation_type', models.CharField(max_length=100)),
                ('revenue_loss', models.FloatField()),
                ('risk_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('recommendation', models.TextField()),
                ('business_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weatherApp.businessdata')),
            ],
        ),
        migrations.AddField(
            model_name='businessdata',
            name='weather_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weatherApp.weatherdata'),
        ),
    ]
